config/routes.rb
NatureAtBest::Application.routes.draw do
  root :to=>"home#naturehomepage"

  get "store/index"
  get "home/naturehomepage"
  get "products/show"
  get "carts/index"
  get "line_items/show"

  resources :products
  resources :producttypes
  resources :carts
  resources :line_items

  
  

end

app/models/cart.rb
class Cart < ActiveRecord::Base
   # attr_accessible :cart.id
   attr_accessor :cart_item_count
  has_many :line_items, dependent: :destroy
end

public
def add_product(product_id)
	current_item = line_items.find_by_product_id(product_id)
	if current_item
		current_item.quantity += 1
	else
		current_item = line_items.build(product_id: product_id)
	end
	# current_item
end

app/controllers/carts_controller.rb
require 'uri'
require 'cgi'

class CartsController < ApplicationController

  include ActiveModel::MassAssignmentSecurity

  # def current_cart
  #   Cart.find(session[:cart_id])
  # rescue ActiveRecord::RecordNotFound
  #   cart = Cart.create
  #   session[:cart_id] = cart_id
  #   cart
  # end
  
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:id])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

# Destroying the whole set
    # def destroy
    #    # @cart = Cart.find(params[:id])
    #    @cart.destroy

    #    respond_to do |format|
    #      format.html { redirect_to carts_url }
    #      format.json { head :no_content }
    #    end
    # end

# Destroying one item 
  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
    format.html { redirect_to carts_url }
     format.json { head :no_content }
     end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
   <% @cart.line_items.each do |item| %> 
   <ul>
      <li>
        <%= item.product.id%>
      </li>
    </ul> 
   <% end %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Products', products_path(:prodtype => 'Picture') %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>


<!--<% @carts.each do |cart| %> -->
  <!-- Need to include product image for better cart display-->

  <% @cart.line_items.each do |item| %> 
   <ul>
      <li>
        <%= item.product.id%>
      </li>
    </ul> 
   <% end %>
   
  <table> 
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?'} %></td>
  </tr>
</table>

<br />

<!-- <%= link_to 'New Cart', new_cart_path %> -->

<%= link_to 'Edit', @product %> |
<%= link_to 'Back', products_path %>
<%= link_to 'Products', products_path(:prodtype => 'Picture') %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
	<p id="notice"><%= notice %></p>
<% end %>

<h2>Your Cart items</h2>
<ul>
	<% @cart.line_items.each do |item| %>  
	<!-- Need to include product image for better cart display-->
		<li><%= item.product.id%></li>	
		<li><%= item.quantity %> &times; <%= item.product.prod_desc %></li>
	<% end %>
</ul>

<%= link_to 'Edit', edit_cart_path(@cart) %>  |
<%= link_to 'Products', products_path(:prodtype => 'Picture') %>