config/routes.rb
NatureAtBest::Application.routes.draw do
  root :to=>"home#naturehomepage"

  get "store/index"
  get "home/naturehomepage"
  get "products/show"
  get "carts/index"
  get "line_items/show"

  resources :products
  resources :producttypes
  resources :carts
  resources :line_items

  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :prod_desc, :prod_img, :prod_name, :prod_price, :ProdType

  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
  	if line_items.empty?
  		return true
  	else
  		errors.add(:base, 'Line Items present')
  		return false
  	end

  end
end

app/models/producttype.rb
class Producttype < ActiveRecord::Base
  attr_accessible :title
end

app/controllers/products_controller.rb
require 'uri'
require 'cgi'

class ProductsController < ApplicationController
  include ActiveModel::MassAssignmentSecurity
# GET /products/productshomepage
  # GET /products.json
  def producthomepage
    @products = producttypes.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products
  # GET /products.json
  def index
    if params[:prodtype].blank?
      @products = Product.all
  else
      @products = Product.where(:ProdType => params[:prodtype])
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end


  # def show_by_type
  #   @product = Product.where(:ProdType => params[:prodtype])

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @product, :location  => "index"}
  #   end
  # end


  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<table>
  
    <%= form_for(@product) do |f| %>
      <% if @product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
          <% @product.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %> 
    <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
      <td><%= f.label :prod_name %></td>
      <td><%= f.text_field :prod_name %></td>
    </tr>
    <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
      <td><%= f.label :prod_desc %></td>
      <td><%= f.text_area :prod_desc %></td>
    </tr>
    <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
      <td><%= f.label :prod_price %></td>
      <td><%= f.text_field :prod_price %></td>
    </tr>
    <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
      <td><%= f.label :prod_img %></td>
      <td><%= f.text_field :prod_img %></td>
    </tr>
    <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
      <td><%= f.label :ProdType %></td>
      <td><%= f.text_field :ProdType %></td>
    </tr>
    <tr >
      <td><%= f.submit %></td>
    </tr>
    <% end %>

</table>

app/views/products/edit.html.erb
<h2> Edit product selected: </h2>
<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% if params[:prodtype].blank? %>
  <h1>Listing products -  "All" </h1>
<%else%>
  <h1> Listing products -  <%= "#{params[:prodtype]}"%> </h1>
<%end%>

<table>
  <% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd','list_line_even') %>">
    <td>
      <%= image_tag(product.prod_img, class: 'list_image')%>
    </td>

    <td class="list_description">
      <dl>
        <dt><%= product.prod_name %></dt>
        <dd><%= truncate(strip_tags(product.prod_desc), length:80) %></dd>
      </dl>
    </td>

    <td>   
        <%= "price:"+ number_to_currency("#{product.prod_price}") %>
    </td>
    <td>
    
      <%= "product Type: #{product.ProdType}" %>

    </td> 

    <td class="list_actions">
      <%= link_to 'Show', product %><br/>
      <%= link_to 'Edit', edit_product_path(product) %><br/>
      <%= link_to 'Destroy', product, confirm: 'Are you sure?', method: :delete %>
      <%= button_to 'Add to Cart', line_items_path(product_id: product) %>
    </td>

  </tr>
  <% end %>
</table> 

<br />

<!-- New product is added only for all products-->
<% if params[:prodtype].blank? %>
  <p><%= link_to 'New Product', new_product_path %></p>
<%end%>

<p><%= link_to 'Back', home_naturehomepage_path %></p>

app/views/products/new.html.erb
<h2>Add New product:</h2>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h2> Product you selected: </h2>
<!-- <p id="notice"><%= notice %></p> -->

<table >
  <tr class = "<%= cycle('list_line_odd','list_line_even')%>" >
    <td><b>Title:</b></td>
    <td><%= @product.prod_name  %></td>
  </tr>
  <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
    <td>Description:</td>
    <td><%= @product.prod_desc %></td>
  </tr>
  <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
    <td>Image :</td>
    <td > <%= image_tag(@product.prod_img, class: 'list_image') %> </td>
  </tr>
  <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
    <td>Price:</td>
    <td><%= number_to_currency(@product.prod_price) %></td>
  </tr>
  <tr class = "<%= cycle('list_line_odd','list_line_even')%>">
    <td><b>Type:</b></td>
    <td><%= @product.ProdType  %></td>
  </tr>

</table> 
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>